export const actionType = {
  ADD_POKEMON: 'ADD-POKEMON',
  UPDATE_PAGINATION: 'UPDATE-PAGINATION',
  UPDATE_TEXT_SEARCH: 'UPDATE-TEXT-SEARCH',
  ADD_MESSAGE: 'ADD-MESSAGE',
  RESET_MESSAGE: 'RESET-MESSAGE'
}